import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    default: "Kanabuet Steel",
    template: "%s | Kanabuet Steel"
  },
  description:
    "Sistem informasi manajemen proyek bengkel las konstruksi untuk memantau progres pekerjaan, lokasi proyek, material, serta dokumentasi proyek secara terpusat.",
  keywords: [
    "manajemen proyek",
    "bengkel las",
    "konstruksi baja",
    "project management",
    "kanabuet steel"
  ],
  authors: [{ name: "Kanabuet Steel" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
